name: Dojo Contracts CI
on:
  push:
    paths:
      - ".github/workflows/contracts.yaml"
      - "dojo-starter/**"
      - "Scarb.toml"
  pull_request:
    branches:
      - main
    paths:
      - "dojo-starter/**"
      - "Scarb.toml"
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: [lts/*]
    env:
      DOJO_VERSION: v1.0.2
    steps:
      - uses: actions/checkout@v3
      - run: curl -L https://install.dojoengine.org | bash
      - run: /home/runner/.config/.dojo/bin/dojoup -v ${{ env.DOJO_VERSION }}

      - name: Run Dojo Build
        run: |
          cd dojo-starter && sozo build

      - name: Run Dojo Test for ${{ matrix.test }}
        run: |
          cd dojo-starter && sozo test

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.4"

      - name: Check Code Format
        run: cd dojo-starter && scarb fmt --check
