name: Dojo Contracts CI

on:
  push:
    paths:
      - ".github/workflows/contracts.yaml"
      - "dojo-starter/**"
      - "Scarb.toml"
  pull_request:
    branches:
      - main
    paths:
      - "dojo-starter/**"
      - "Scarb.toml"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: [lts/*]

    steps:
      - name: Install dojo
        run: |
          curl -L -o dojo-linux-x86_64.tar.gz https://github.com/dojoengine/dojo/releases/download/v1.0.2/dojo_v1.0.5_linux_amd64.tar.gz
          tar -xzf dojo-linux-x86_64.tar.gz
          sudo mv sozo /usr/local/bin/
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Dojo Build
        run: |
          cd dojo-starter && sozo build
      - name: Run Dojo Test for ${{ matrix.test }}
        run: |
          cd dojo-starter && sozo test

      - name: Check Code Format
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.4"
        run: cd dojo-starter && scarb fmt --check
